trigger:
    - develop

pool:
    vmImage: ubuntu-latest

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: '16.x'
      displayName: 'Install Node.js'

    - task: npmAuthenticate@0
      inputs:
          workingFile: .npmrc
          customEndpoint: sharptree-npm
      displayName: 'Authorize with private npm using root npmrc'

    - script: |
          npm run install
      displayName: 'npm install'

    - script: |
          npm run build
      displayName: 'npm build'

    - task: Npm@1
      inputs:
          command: publish
          publishRegistry: useExternalRegistry
          publishEndpoint: 'sharptree-npm'
