trigger:
    - develop

pool:
    vmImage: ubuntu-latest

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: '16.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      inputs:
          command: install
          customRegistry: useExternalRegistry
          customEndpoint: 'sharptree-npm'

    - script: |
          npm run build
      displayName: 'npm build'

    - task: Npm@1
      inputs:
          command: publish
          publishRegistry: useExternalRegistry
          publishEndpoint: 'sharptree-npm'
